version: '3'
services:
#  app:
#    container_name: app
#    build: .
#    ports:
#      - "5000:5000"
#    networks:
#      - frontend
  grafana:
    container_name: grafana
    image: 'grafana/grafana:5.4.3'
    volumes:
      - './data/grafana:/var/lib/grafana'
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
    ports:
      - "3000:3000"
    networks:
      - frontend
  influxdb:
    container_name: influxdb
    image: "influxdb:1.7"
    environment:
      - "INFLUXDB_GRAPHITE_ENABLED=true"
      - "INFLUXDB_ADMIN_ENABLED=true"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=admin"
      - "INFLUXDB_DB=db0"
    networks:
      - frontend
    volumes:
      - './data/influxdb.conf:/etc/influxdb/influxdb.conf:ro'
      - './data/influxdb:/var/lib/influxdb'
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    links:
      - grafana
networks:
  frontend:
